In [1]:
import numpy as np
import pandas as pd

In [3]:
dota_heroes = pd.read_csv('dota_hero_stats.csv')

In [4]:
dota_heroes

,Unnamed: 0,attack_type,id,legs,localized_name,name,primary_attr,roles
0,0,Melee,1,2,Anti-Mage,npc_dota_hero_antimage,agi,"['Carry', 'Escape', 'Nuker']"
1,1,Melee,2,2,Axe,npc_dota_hero_axe,str,"['Initiator', 'Durable', 'Disabler', 'Jungler']"
2,2,Ranged,3,4,Bane,npc_dota_hero_bane,int,"['Support', 'Disabler', 'Nuker', 'Durable']"
3,3,Melee,4,2,Bloodseeker,npc_dota_hero_bloodseeker,agi,"['Carry', 'Disabler', 'Jungler', 'Nuker', 'Ini..."
4,4,Ranged,5,2,Crystal Maiden,npc_dota_hero_crystal_maiden,int,"['Support', 'Disabler', 'Nuker', 'Jungler']"
...,...,...,...,...,...,...,...,...
112,112,Melee,114,2,Monkey King,npc_dota_hero_monkey_king,agi,"['Carry', 'Escape', 'Disabler', 'Initiator']"
113,113,Ranged,119,2,Dark Willow,npc_dota_hero_dark_willow,int,"['Support', 'Nuker', 'Disabler', 'Escape']"
114,114,Melee,120,2,Pangolier,npc_dota_hero_pangolier,agi,"['Carry', 'Nuker', 'Disabler', 'Durable', 'Esc..."
115,115,Ranged,121,2,Grimstroke,npc_dota_hero_grimstroke,int,"['Support', 'Nuker', 'Disabler', 'Escape']"
116,116,Melee,129,2,Mars,npc_dota_hero_mars,str,"['Carry', 'Initiator', 'Disabler', 'Durable']"

In [6]:
zero_legs = dota_heroes.query('legs == 0')
zero_legs

,Unnamed: 0,attack_type,id,legs,localized_name,name,primary_attr,roles
9,9,Ranged,10,0,Morphling,npc_dota_hero_morphling,agi,"['Carry', 'Escape', 'Durable', 'Nuker', 'Disab..."
10,10,Ranged,11,0,Shadow Fiend,npc_dota_hero_nevermore,agi,"['Carry', 'Nuker']"
14,14,Ranged,15,0,Razor,npc_dota_hero_razor,agi,"['Carry', 'Durable', 'Nuker', 'Pusher']"
26,26,Melee,28,0,Slardar,npc_dota_hero_slardar,str,"['Carry', 'Durable', 'Initiator', 'Disabler', ..."
31,31,Ranged,33,0,Enigma,npc_dota_hero_enigma,int,"['Disabler', 'Jungler', 'Initiator', 'Pusher']"
38,38,Ranged,40,0,Venomancer,npc_dota_hero_venomancer,agi,"['Support', 'Nuker', 'Initiator', 'Pusher', 'D..."
45,45,Ranged,47,0,Viper,npc_dota_hero_viper,agi,"['Carry', 'Durable', 'Initiator', 'Disabler']"
65,65,Melee,67,0,Spectre,npc_dota_hero_spectre,agi,"['Carry', 'Durable', 'Escape']"
87,87,Melee,89,0,Naga Siren,npc_dota_hero_naga_siren,agi,"['Carry', 'Support', 'Pusher', 'Disabler', 'In..."
89,89,Ranged,91,0,Io,npc_dota_hero_wisp,str,"['Support', 'Escape', 'Nuker']"
92,92,Ranged,94,0,Medusa,npc_dota_hero_medusa,agi,"['Carry', 'Disabler', 'Durable']"

In [13]:
num_zero_legs = zero_legs.shape[0]
num_zero_legs

11

In [15]:
two_legs = dota_heroes.query('legs == 2')
two_legs

,Unnamed: 0,attack_type,id,legs,localized_name,name,primary_attr,roles
0,0,Melee,1,2,Anti-Mage,npc_dota_hero_antimage,agi,"['Carry', 'Escape', 'Nuker']"
1,1,Melee,2,2,Axe,npc_dota_hero_axe,str,"['Initiator', 'Durable', 'Disabler', 'Jungler']"
3,3,Melee,4,2,Bloodseeker,npc_dota_hero_bloodseeker,agi,"['Carry', 'Disabler', 'Jungler', 'Nuker', 'Ini..."
4,4,Ranged,5,2,Crystal Maiden,npc_dota_hero_crystal_maiden,int,"['Support', 'Disabler', 'Nuker', 'Jungler']"
5,5,Ranged,6,2,Drow Ranger,npc_dota_hero_drow_ranger,agi,"['Carry', 'Disabler', 'Pusher']"
...,...,...,...,...,...,...,...,...
112,112,Melee,114,2,Monkey King,npc_dota_hero_monkey_king,agi,"['Carry', 'Escape', 'Disabler', 'Initiator']"
113,113,Ranged,119,2,Dark Willow,npc_dota_hero_dark_willow,int,"['Support', 'Nuker', 'Disabler', 'Escape']"
114,114,Melee,120,2,Pangolier,npc_dota_hero_pangolier,agi,"['Carry', 'Nuker', 'Disabler', 'Durable', 'Esc..."
115,115,Ranged,121,2,Grimstroke,npc_dota_hero_grimstroke,int,"['Support', 'Nuker', 'Disabler', 'Escape']"
116,116,Melee,129,2,Mars,npc_dota_hero_mars,str,"['Carry', 'Initiator', 'Disabler', 'Durable']"

In [16]:
num_two_legs = two_legs.shape[0]
num_two_legs

95

In [17]:
four_legs = dota_heroes.query('legs == 4')
four_legs

,Unnamed: 0,attack_type,id,legs,localized_name,name,primary_attr,roles
2,2,Ranged,3,4,Bane,npc_dota_hero_bane,int,"['Support', 'Disabler', 'Nuker', 'Durable']"
50,50,Ranged,52,4,Leshrac,npc_dota_hero_leshrac,int,"['Carry', 'Support', 'Nuker', 'Pusher', 'Disab..."
56,56,Ranged,58,4,Enchantress,npc_dota_hero_enchantress,int,"['Support', 'Jungler', 'Pusher', 'Durable', 'D..."
61,61,Ranged,63,4,Weaver,npc_dota_hero_weaver,agi,"['Carry', 'Escape']"
74,74,Ranged,76,4,Outworld Devourer,npc_dota_hero_obsidian_destroyer,int,"['Carry', 'Nuker', 'Disabler']"
94,94,Melee,96,4,Centaur Warrunner,npc_dota_hero_centaur,str,"['Durable', 'Initiator', 'Disabler', 'Nuker', ..."
95,95,Melee,97,4,Magnus,npc_dota_hero_magnataur,str,"['Initiator', 'Disabler', 'Nuker', 'Escape']"

In [19]:
num_four_legs = four_legs.shape[0]
num_four_legs

7

In [21]:
six_legs = dota_heroes.query('legs == 6')
six_legs

,Unnamed: 0,attack_type,id,legs,localized_name,name,primary_attr,roles
15,15,Melee,16,6,Sand King,npc_dota_hero_sand_king,str,"['Initiator', 'Disabler', 'Support', 'Nuker', ..."
86,86,Melee,88,6,Nyx Assassin,npc_dota_hero_nyx_assassin,agi,"['Disabler', 'Nuker', 'Initiator', 'Escape']"
103,103,Ranged,105,6,Techies,npc_dota_hero_techies,int,"['Nuker', 'Disabler']"

In [22]:
num_six_legs = six_legs.shape[0]
num_six_legs

3

In [23]:
eight_legs = dota_heroes.query('legs == 8')
eight_legs

,Unnamed: 0,attack_type,id,legs,localized_name,name,primary_attr,roles
59,59,Melee,61,8,Broodmother,npc_dota_hero_broodmother,agi,"['Carry', 'Pusher', 'Escape', 'Nuker']"

In [25]:
num_eight_legs = eight_legs.shape[0]
num_eight_legs

1

In [41]:
attr = dota_heroes.groupby(['attack_type', 'primary_attr']).aggregate({'Unnamed: 0' : 'count'})

In [42]:
attr

                          Unnamed: 0
attack_type primary_attr
Melee       agi                   19
            int                    2
            str                   35
Ranged      agi                   18
            int                   40
            str                    3